#!/bin/bash
#Pre-checks
#Edited : Jiji Gaonkar.

( echo "date";
date;
echo " ";
echo "w ";
w;
echo " ";
echo "hostname ";
hostname;
echo " ";
echo "dmidecode -t1";
dmidecode -t1;
echo " ";
echo "ifconfig -a";
ifconfig -a;
echo " ";
echo "route -n";
route -n;
echo " ";
echo "df -hTP";
df -hTP;
echo " ";
echo "sestatus";
sestatus;
echo " ";
echo "iptables -L -n";
iptables -L -n;
echo " ";
echo "cat /etc/redhat-release";
cat /etc/redhat-release;
echo " ";
echo "cat /etc/issue";
cat /etc/issue;
echo " ";
echo "free -m";
free -m;
echo " ";
echo "uname -a";
uname -a;
echo " ";
echo "netstat -tulpn";
netstat -tulpn;
echo " ";
echo "lsblk ";
lsblk;
echo " ";
echo "cat /etc/fstab";
cat /etc/fstab;
echo " ";
echo "cat /etc/rc.local";
cat /etc/rc.local;
echo " ";
echo "cat /etc/hosts";
cat /etc/hosts;
echo " ";
echo "cat /etc/resolv.conf";
cat /etc/resolv.conf;
echo " ";
echo "cat /etc/hosts.allow";
cat /etc/hosts.allow;
echo " ";
echo "cat /etc/hosts.deny";
cat /etc/hosts.deny;
echo " ";
echo "pvs";
pvs;
echo " ";
echo "vgs";
vgs;
echo " ";
echo "lvs";
lvs;
echo " ";
echo "multipath -ll";
multipath -ll;
echo " ";
echo "iscsiadm -m session ";
iscsiadm -m session;
echo " ";
echo "iscsiadm -m session |wc -l ";
iscsiadm -m session |wc -l;
echo " ";
echo "ps -ef";
ps -ef;
echo " ";
echo "crontab -l";
crontab -l;
echo " ";
echo "postfix status";
service postfix status;
echo " ";
echo "caagent status";
caagent status;
echo " ";
echo "uagent status";
uagent status;
echo " ";
echo "ntpq -pn";
ntpq -pn ; cat /etc/ntp.conf |egrep "^server";
echo " ";
echo "Chrony";
chronyc tracking; chronyc sources ; cat /etc/chrony.conf |egrep "^server";
echo " ";
echo "cat /etc/yum.conf";
cat /etc/yum.conf;
echo " ";
echo "ls /etc/sysconfig/network-scripts/ifcfg-*";
ls /etc/sysconfig/network-scripts/ifcfg-*;
echo " ";
echo "cat /etc/sysconfig/network-scripts/ifcfg-";
cat /etc/sysconfig/network-scripts/ifcfg-*;
echo " ";
echo "multipath -ll |wc -l";
multipath -ll |wc -l;
echo " ";
echo "netstat -tulpn |wc -l";
netstat -tulpn |wc -l;
echo " ";
echo "ip addr sh";
ip addr sh;
echo " ";
echo "mount -av";
mount -av;
echo " ";
echo "sshd -t";
sshd -t;
echo " "; ) > $(date +'%d-%m-%y').txt

